### ISSUE TITLE
Falsely finds roborio via static ip address

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/java-installer#17]
When I'm on a network with a 10.* network with a netmask of 255.0.0.0 that does not have a roborio, the eclipse deploy reports that it found the roboRIO via Ethernet static.

When this occurs, and I ping the supposed IP address, ping reports destination host unreachable.

This appears to be an issue with the java isReachable method and same root cause as wpilibsuite/EclipsePlugins#65

**Comment by AustinShalit** [comment]
wpilibsuite/EclipsePlugins#64

(Just so github generates a link)

**Comment by 333fred** [comment]
https://github.com/wpilibsuite/EclipsePlugins/issues/65

**Comment by sciencewhiz** [comment]
This seems to be an artifact of how Window switches networks
